name: ci

on:
  pull_request:
    branches: [main]

jobs:
   tests:
     name: Tests
     runs-on: ubuntu-latest
     steps:
       - name: Check out code
         uses: actions/checkout@v4

       - name: Set up Go
         uses: actions/setup-go@v5
         with:
           go-version: "1.23.0"
       - name: Tests
         run: go test ./... -cover
       - name: Install gosec
         run: go install github.com/securego/gosec/v2/cmd/gosec@latest
       - name: gosec
         run: gosec ./...
   Style:
     name: Style
     runs-on: ubuntu-latest
     
     steps:
       - name: Check out code
         uses: actions/checkout@v4
       - name: Set up go
         uses: actions/setup-go@v5
       - name: Test formatting
         run: test -z $(go fmt ./...)
       - name: Install staticcheck
         run: go install honnef.co/go/tools/cmd/staticcheck@latest
       - name: Format go
         run: go fmt ./...
       - name: Lint code
         run: staticcheck ./...

